version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:latest
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/calculator_dir
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
